project_id          = "quantai-trading"
environment         = "paper"
region              = "asia-southeast1"
bigquery_dataset_id = "quantai_trading"
gcs_backup_bucket   = "quantai-backups-quantai-trading"
alert_email         = "chonnaveesukyao@gmail.com"
