# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trading.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trading.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtrading.proto\x12\x07trading\"\x92\x01\n\rSignalRequest\x12\x13\n\x0bstrategy_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x11\n\tdirection\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x01\x12\x11\n\tstop_loss\x18\x05 \x01(\t\x12\x10\n\x08quantity\x18\x06 \x01(\t\x12\x15\n\rcurrent_price\x18\x07 \x01(\t\"U\n\x0eSignalResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x0f\n\rHealthRequest\"z\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x12\n\npaper_mode\x18\x02 \x01(\x08\x12\x17\n\x0fportfolio_value\x18\x03 \x01(\t\x12\x13\n\x0bopen_orders\x18\x04 \x01(\x05\x12\x15\n\rpubsub_active\x18\x05 \x01(\x08\x32\x90\x01\n\rTradingBridge\x12?\n\x0cSubmitSignal\x12\x16.trading.SignalRequest\x1a\x17.trading.SignalResponse\x12>\n\x0bHealthCheck\x12\x16.trading.HealthRequest\x1a\x17.trading.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trading_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNALREQUEST']._serialized_start=27
  _globals['_SIGNALREQUEST']._serialized_end=173
  _globals['_SIGNALRESPONSE']._serialized_start=175
  _globals['_SIGNALRESPONSE']._serialized_end=260
  _globals['_HEALTHREQUEST']._serialized_start=262
  _globals['_HEALTHREQUEST']._serialized_end=277
  _globals['_HEALTHRESPONSE']._serialized_start=279
  _globals['_HEALTHRESPONSE']._serialized_end=401
  _globals['_TRADINGBRIDGE']._serialized_start=404
  _globals['_TRADINGBRIDGE']._serialized_end=548
# @@protoc_insertion_point(module_scope)
